spring:
  application:
    name: cloud-payment-service
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
server:
  port: 8006